package kml

const SubplaceTypeAll = "N"

// Generated by https://quicktype.io

type Response struct {
	Landmark  Landmark   `json:"landmark"`
	Subplaces []Subplace `json:"subplaces"`
}

type Landmark struct {
	NameEn            string           `json:"name_en"`
	NameID            string           `json:"name_id"`
	Address           string           `json:"address"`
	City              string           `json:"city"`
	Type              string           `json:"type"`
	StartDate         string           `json:"start_date"`
	EndDate           string           `json:"end_date"`
	IsActive          bool             `json:"is_active"`
	Restricted        bool             `json:"restricted"`
	PredefinedDropoff bool             `json:"predefined_dropoff"`
	Geometry          ResponseGeometry `json:"geometry"`
}

type ResponseGeometry struct {
	Type        string        `json:"type"`
	Coordinates [][][]float64 `json:"coordinates"`
}

type Subplace struct {
	NameEn         string    `json:"name_en"`
	NameID         string    `json:"name_id"`
	IsServicePoint bool      `json:"is_service_point"`
	SubplaceType   string    `json:"subplace_type"`
	Location       []float64 `json:"location"`
}

func GetGeometry(coordinates [][][]float64) ResponseGeometry {
	return ResponseGeometry{
		Type:        "Polygon",
		Coordinates: coordinates,
	}
}
