package geojson

// Generated by https://quicktype.io

type Request struct {
	Type     string           `json:"type"`
	Features []FeatureElement `json:"features"`
}

type FeatureElement struct {
	Type       FeatureType `json:"type"`
	Geometry   Geometry    `json:"geometry"`
	Properties Properties  `json:"properties"`
}

type Geometry struct {
	Type        GeometryType `json:"type"`
	Coordinates interface{}  `json:"coordinates"`
}

type Properties struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type GeometryType string

const (
	Point   GeometryType = "Point"
	Polygon GeometryType = "Polygon"
)

type FeatureType string

const (
	Feature FeatureType = "Feature"
)

type Coordinate struct {
	Double           *float64
	DoubleArrayArray [][]float64
}

func (c Coordinate) Location() float64 {
	if c.Double == nil {
		return 0
	}

	return *c.Double
}
